version: "3.8"

services:
  express:
    build: .
    container_name: express-app
    restart: always
    expose:
      - "5000"
  
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - express
